#!/bin/bash
# my simple script to check HTTP connection counts
# result format: [conn_count],ESTABLISHED_count,TIMEWAIT_count

WARN="400"
CRIT="600"

nc -nzw2 127.0.0.1 80 > /dev/null && port='80'
nc -nzw2 127.0.0.1 8080 > /dev/null && port='8080'

[ -f /tmp/httpconn ] && sudo rm -f /tmp/httpconn
netstat -an | awk '$4~/:'$port'/{print}' > /tmp/httpconn

CONNS=`cat /tmp/httpconn |wc -l`
ESTABLISHED=`grep "ESTABLISHED" /tmp/httpconn |wc -l`
TIME_WAIT=`grep "TIME_WAIT" /tmp/httpconn |wc -l`

if test "$CONNS"
then
        if [ "$CONNS" -ge "$CRIT" ]
        then
                echo "CRITICAL - HTTP connections have excceeded $CRIT. Current connections: [$CONNS],$ESTABLISHED,$TIME_WAIT"
                exit 2
        elif [ "$CONNS" -ge "$WARN" ] && [ "$CONNS" -lt "$CRIT" ]
        then
                echo "WARNING - HTTP connections have excceeded $WARN. Current connections: [$CONNS],$ESTABLISHED,$TIME_WAIT"
                exit 1
        else
                echo "HTTP connections OK. Current connections: [$CONNS],$ESTABLISHED,$TIME_WAIT"
        fi
else
        echo "Unable to count connections to port $port."
        exit 3
fi
